// export const ActionType = {
//   SET_PRODUCT: "SET_PRODUCT",
//   SELECTED_PRODUCT: "SELECTED_PRODUCT",
//   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
// };



export const ActionTypes = {
  FETCH_PRODCTS: "FETCH_PRODCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
   SET_SEARCH_TERM : 'SET_SEARCH_TERM'
};



