const ActionTypes = {
  FETCH_PRODUCE: "FETCH_PRODUCE",
  SET_PRODUCE: "SET_PRODUCE",
  SELECTED_PRODUCE: "SELECTED_PRODUCE",
  REMOVE_SELECTED_PRODUCE: "REMOVE_SELECTED_PRODUCE",
};

export default ActionTypes;
