export const ActionTypes = {
    FETCH_SET_PRODUCT: "FETCH_SET_PRODUCT",
    SET_PRODUCT: "SET_PRODUCT",
    SELECTE_PRODUCT: "SELECTE_PRODUCT",
    REMOVE_SELECTE_PRODUCT: "REMOVE_SELECTE_PRODUCT",
  };